FROM public.ecr.aws/docker/library/ruby:2.7.8-alpine3.16

ADD . /app
WORKDIR /app

RUN apk add --no-cache build-base && \
    apk add --no-cache ruby-dev && \
    apk add --no-cache gmp-dev && \
    apk add --no-cache git && \
    bundle install
